# 0.参考URL
# https://qiita.com/willow-micro/items/51eeb3efe5b4192a4abd (ラベル名)
# https://qiita.com/hayashima/items/4e2cfcaf3216f5686003 (ラベル定義)

#---------------------------------------------------------------------------------------------------
# 1.Type 取り組む作業の種別を表すラベル
["Type: Bug Fix"]
color = "ff6666"
name = "Type: Bug Fix"
description = "バグ修正"

["Type: Enhancement"]
color = "ffdb66"
name = "Type: Enhancement"
description = "新機能追加"

["Type: Improvement"]
color = "66baff"
name = "Type: Improvement"
description = "改良修正(処理の安定化など)"

["Type: Optimization"]
color = "669eff"
name = "Type: Optimization"
description = "最適化(処理の高速化など)"

["Type: Security Fix"]
color = "ff6666"
name = "Type: Security Fix"
description = "セキュリティ問題の修正"

#---------------------------------------------------------------------------------------------------
# 2.Status 状態を表すラベル
["Status: Available"]
color = "87a9c0"
name = "Status: Available"
description = "待機中"

["Status: In Progress"]
color = "bec680"
name = "Status: In Progress"
description = "作業中"

["Status: Completed"]
color = "81c785"
name = "Status: Completed"
description = "作業完了"

["Status: Canceled"]
color = "808ac6"
name = "Status: Canceled"
description = "作業中止"

["Status: Duplicate"]
color = "89a3a9"
name = "Status: Duplicate"
description = "Issue重複"

["Status: Pending"]
color = "80b399"
name = "Status: Pending"
description = "保留"

#---------------------------------------------------------------------------------------------------
# 3.Priority 優先度を表すラベル
["Priority: ASAP"]
color = "ff6666"
name = "Priority: ASAP"
description = "最優先"

["Priority: High"]
color = "ff8a65"
name = "Priority: High"
description = "優先度: 高"

["Priority: Medium"]
color = "ffd166"
name = "Priority: Medium"
description = "優先度: 中"

["Priority: Low"]
color = "dce775"
name = "Priority: Low"
description = "優先度: 低"

["Priority: Safe"]
color = "81c785"
name = "Priority: Safe"
description = "余裕があれば取り組む"

#---------------------------------------------------------------------------------------------------
# 4.Effort 作業量を表すラベル
["Effort: Painful"]
color = "ff6666"
name = "Effort: Painful"
description = "作業量: 膨大"

["Effort: Heavy"]
color = "ff8a65"
name = "Effort: Heavy"
description = "作業量: 多"

["Effort: Normal"]
color = "ffd166"
name = "Effort: Normal"
description = "作業量: 中"

["Effort: Light"]
color = "dce775"
name = "Effort: Light"
description = "作業量: 少"

["Effort: Effortless"]
color = "81c785"
name = "Effort: Effortless"
description = "作業量: ほぼ無し"

#---------------------------------------------------------------------------------------------------
# 5.Feedback フィードバックの種類を表すラベル
["Feedback: Discussion"]
color = "f06293"
name = "Feedback: Discussion"
description = "機能に関する議論"

["Feedback: Question"]
color = "f06293"
name = "Feedback: Question"
description = "機能に関する質問"

["Feedback: Suggestion"]
color = "f06293"
name = "Feedback: Suggestion"
description = "機能に関する提案"

