# 0.参考URL FromQiita
# https://qiita.com/willow-micro/items/51eeb3efe5b4192a4abd (ラベル名)
# https://qiita.com/hayashima/items/4e2cfcaf3216f5686003 (ラベル定義)

#---------------------------------------------------------------------------------------------------
# 1.Type 取り組む作業の種別を表すラベル
["Type: Bug Fix"]
color = "ff6666"
name = "Type: 1-Bug Fix"
description = "バグ修正"

["Type: Enhancement"]
color = "ffdb66"
name = "Type: 2-Enhancement"
description = "新機能追加"

["Type: Improvement"]
color = "66baff"
name = "Type: 3-Improvement"
description = "改良修正(処理の安定化など)"

["Type: Optimization"]
color = "669eff"
name = "Type: 4-Optimization"
description = "最適化(処理の高速化など)"

["Type: Security Fix"]
color = "ff6666"
name = "Type: 5-Security Fix"
description = "セキュリティ問題の修正"

#---------------------------------------------------------------------------------------------------
# 2.Status 状態を表すラベル
["Status: Available"]
color = "87a9c0"
name = "Status: 1-Available"
description = "待機中"

["Status: In Progress"]
color = "bec680"
name = "Status: 2-In Progress"
description = "作業中"

["Status: Completed"]
color = "81c785"
name = "Status: 3-Completed"
description = "作業完了"

["Status: Canceled"]
color = "808ac6"
name = "Status: 4-Canceled"
description = "作業中止"

["Status: Duplicate"]
color = "89a3a9"
name = "Status: 5-Duplicate"
description = "Issue重複"

["Status: Pending"]
color = "80b399"
name = "Status: 6-Pending"
description = "保留"

#---------------------------------------------------------------------------------------------------
# 3.Priority 優先度を表すラベル
["Priority: ASAP"]
color = "ff6666"
name = "Priority: 1-ASAP"
description = "最優先"

["Priority: High"]
color = "ff8a65"
name = "Priority: 2-High"
description = "優先度: 高"

["Priority: Medium"]
color = "ffd166"
name = "Priority: 3-Medium"
description = "優先度: 中"

["Priority: Low"]
color = "dce775"
name = "Priority: 4-Low"
description = "優先度: 低"

["Priority: Safe"]
color = "81c785"
name = "Priority: 5-Safe"
description = "余裕があれば取り組む"

#---------------------------------------------------------------------------------------------------
# 4.Effort 作業量を表すラベル
["Effort: Painful"]
color = "ff6666"
name = "Effort: 1-Painful"
description = "作業量: 膨大"

["Effort: Heavy"]
color = "ff8a65"
name = "Effort: 2-Heavy"
description = "作業量: 多"

["Effort: Normal"]
color = "ffd166"
name = "Effort: 3-Normal"
description = "作業量: 中"

["Effort: Light"]
color = "dce775"
name = "Effort: 4-Light"
description = "作業量: 少"

["Effort: Effortless"]
color = "81c785"
name = "Effort: 5-Effortless"
description = "作業量: ほぼ無し"

#---------------------------------------------------------------------------------------------------
# 5.Feedback フィードバックの種類を表すラベル
["Feedback: Discussion"]
color = "f06293"
name = "Feedback: 1-Discussion"
description = "機能に関する議論"

["Feedback: Question"]
color = "f06293"
name = "Feedback: 2-Question"
description = "機能に関する質問"

["Feedback: Suggestion"]
color = "f06293"
name = "Feedback: 3-Suggestion"
description = "機能に関する提案"

