["Status: Available"]
color = "87a9c0"
name = "Status: Available"
description = "待機中"

["Status: Canceled"]
color = "808ac6"
name = "Status: Canceled"
description = "作業中止"

["Status: Completed"]
color = "81c785"
name = "Status: Completed"
description = "作業完了"

["Status: In Progress"]
color = "bec680"
name = "Status: In Progress"
description = "作業中"

["Type: Bug Fix"]
color = "ff6666"
name = "Type: Bug Fix"
description = "バグ修正"

["Type: Enhancement"]
color = "ffdb66"
name = "Type: Enhancement"
description = "新機能追加"

["Type: Improvement"]
color = "66baff"
name = "Type: Improvement"
description = "改良修正(処理の安定化など)"

["Type: Optimization"]
color = "669eff"
name = "Type: Optimization"
description = "最適化(処理の高速化など)"

["Type: Security Fix"]
color = "ff6666"
name = "Type: Security Fix"
description = "セキュリティ問題の修正"
